language: python

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

python:
  - 3.8

install:
  - pip install pip -U
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - pip install codecov
  - poetry install -v

before_script: ./scripts/start_db.sh && sleep 3
script: poetry run pytest --cov=fastapi_simple_login test/

